### ISSUE TITLE
Task: 

### ISSUE THREAD

**Issue by ReinderVosDeWael** [childmindresearch/ctk-api#111]
### Description

Tasks based on feedback received from the clinician.

### Tasks

- [ ] Default to the first name for the child, not nickname. 
- [ ] Add IEP info to the report.  
- [ ] Remove school specifier i.e. remove "private school", "boarding school" etc...
- [ ] Replace parent full name with mr/ms/mrs
  - [ ] Bonus: see if this can be automatically extracted from a combination of gender of guardian relationship + marital status. 
- [ ] Cesarean section - specify the reason. 
- [ ] Use font color for real template vs. filled in.
- [ ] Reason for visit, leave blank the parent inputs. 
- [ ] IEP in educational history add the date.
- [ ] Add names in hope and adaptive functioning of people in household, only for the parents. For siblings remove grade. 
- [ ] Family psychiatric history: revert to template.
